[package]
name = "portfolio"
version = "0.1.0"
edition = "2021"
title = "Alex Bzdel - Portfolio"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
