[package]
authors = ["Alex Bzdel"]
version = "0.1.0"
edition = "2021"
src = "src"
title = "Alex Bzdel - Portfolio"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
